language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

install:
  - composer self-update
  - composer global require "fxp/composer-asset-plugin:1.0.0"
  - composer install --prefer-dist --dev
  - composer info --installed

script: phpunit --configuration phpunit.xml.dist
