language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

sudo: false

before_script:
  - composer self-update
  - composer global require "fxp/composer-asset-plugin:*"
  - composer update
  - composer info --installed

script: phpunit -c phpunit.xml.dist