language: php

php:
#  - 5.4
#  - 5.5
#  - 5.6
  - 7
#  - hhvm

sudo: false

before_script:
  - composer self-update
  - composer global require "fxp/composer-asset-plugin:*"
  - composer update
  - composer info --installed

script: phpunit -c phpunit.xml.dist