language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - 7
  - hhvm
install:
  - composer self-update
  - composer update --ignore-platform-reqs
  - composer info --installed
script: phpunit -c phpunit.xml.dist